# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 3m
  skip-dirs:
    - internal/testing/fixtures

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - gosec
    - unconvert
    - gocritic
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/meta-mcp/meta-mcp-server
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: internal/testing
      linters:
        - gosec